[meta]
name = "Warrior Medals"
author = "Ezio"
category = "Race"
version = "1.10.0"
siteid = 590

[script]
dependencies = [ "NadeoServices" ]
optional_dependencies = [ "MLHook", "UltimateMedalsExtended" ]
module = "WarriorMedals"
exports = [ "src/Export.as" ]
shared_exports = [ "src/ExportShared.as" ]
